spring:
  application:
    name: gateway-zuul
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka
zuul:
  routes:
    consumer: /user/**
  host:
          connect-timeout-millis: 240000
          socket-timeout-millis: 240000