server:
  port: 8082
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
user:
  userServerUrl: http://localhost:8081/**
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule